[package]
name = "rust-cmd-line"
version = "0.0.3"
authors = ["RadoslawWarisch <r.warisch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.7.0"
